[29기 한신웅] 장바구니
wecode-bootcamp-korea/29-1st-BAMIN-SURVIVAL-frontend pull request #12
Opened 2022-02-04 05:51 UTC by hsuj86

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-02-07 08:19 UTC, younuk23 requested changes
고생하셨습니다 신웅님 코드치기전에 미리 잘 생각하고 짜시는게 PR 본문에 잘 드러나는 것 같습니다 👍 
리뷰 확인 및 반영해주세요 :)

2022-02-07 08:19 UTC, younuk23 commented on src/pages/Cart/Cart.js
> +    fetch('http://localhost:3000/data/Shinung/data.json')
localhost:3000은 생략가능합니다! 생략하고 절대경로 시작하게 되면 자연스럽게 현재 프로젝트가 실행되고 있는 URL로 인식이 됩니다.
오히려 기입하게 되면 localhost:3000이 아닌 다른 URL에서 프로젝트가 실행될 때 에러가 발생할 수 있습니다

2022-02-07 08:19 UTC, younuk23 commented on src/pages/Cart/Cart.js
> +    const checkedItem = items.filter(item => item.is_check === true);
```suggestion
    const checkedItem = items.filter(item => item.is_check);
```
item.is_check자체가 이미 boolean 인 것 같네요!

2022-02-07 08:19 UTC, younuk23 commented on src/pages/Cart/Cart.js
> +  const [inputCheck, setInputCheck] = useState(true);
이름을 모든 items가 다 체크되었는지를 잘 나타내는 이름으로 수정하면 좋겠네요!!
그리고 이부분은 굳이 state로 만들필요가 없을 것 같습니다! 라이브코드리뷰 시간에 한번 같이 볼게요

2022-02-07 08:19 UTC, younuk23 commented on src/pages/Cart/CartList.js
> +  const onCheck = id => {
함수 이름은 발생되는 시점이 아니라 함수가 어떤일을 하는지에 대해서 알아볼 수 있도록 지어주는게 좋습니다!

2022-02-07 08:19 UTC, younuk23 commented on src/pages/Cart/TotalAmount.js
> +    .reduce((a, b) => a + b, 0);
👍

2022-02-07 08:19 UTC, younuk23 commented on src/pages/Cart/TotalAmount.js
> +    .filter(item => item.is_check === true)
```suggestion
    .filter(item => item.is_check)
```

2022-02-07 08:20 UTC, younuk23 commented
그리고 추가기능구현중이신가요?? 지금 이 브랜치는 마무리 짓고 추가기능은 새로운 브랜치에서 하시는게 좋아보입니다!

2022-02-07 14:34 UTC, hsuj86 commented on src/pages/Cart/Cart.js
> +    fetch('http://localhost:3000/data/Shinung/data.json')
> localhost:3000은 생략가능합니다! 생략하고 절대경로 시작하게 되면 자연스럽게 현재 프로젝트가 실행되고 있는 URL로 인식이 됩니다. 오히려 기입하게 되면 localhost:3000이 아닌 다른 URL에서 프로젝트가 실행될 때 에러가 발생할 수 있습니다

그렇군요. 그러고보니 3000이상의 숫자가 나올 수도 있으니 절대경로를 해주는게 좋다고 말씀 해주셨던 것 같습니다. 바로 리뷰 반영하였습니다. 감사합니다!

2022-02-07 14:36 UTC, hsuj86 commented on src/pages/Cart/Cart.js
> +    const checkedItem = items.filter(item => item.is_check === true);
> item.is_check자체가 이미 boolean 인 것 같네요!

앗! 그렇네요! 안써도 되는 것을 썼네요 ㅋㅋㅋ 감사합니다! 바로 반영하였습니다!

2022-02-07 14:38 UTC, hsuj86 commented on src/pages/Cart/TotalAmount.js
> +    .filter(item => item.is_check === true)
> 

습관인가 봅니다 ㅋㅋㅋㅋㅋㅋ 😅 다음에는 안쓰겠죠?! ㅋㅋㅋ 감사합니다!

2022-02-07 14:42 UTC, hsuj86 commented on src/pages/Cart/CartList.js
> +  const onCheck = id => {
> 함수 이름은 발생되는 시점이 아니라 함수가 어떤일을 하는지에 대해서 알아볼 수 있도록 지어주는게 좋습니다!

네! 아이템을 체크하는 것이라 itemCheck라고 변경했습니다. 좀 더 좋은 이름이 있는지 생각해보겠습니다! 작명은 항상 고민하게 되네요.

2022-02-07 15:18 UTC, ghost commented on src/pages/Cart/Cart.js
> +import BASE_URL from '../Config';
__[ESLint]__ 'BASE_URL' is defined but never used. ([view](https://sider.review/gh/repos/451356574/pulls/12#issue-6549589))

<details>

| Rule | Severity | Recommended |
| ---- | -------- | ----------- |
| `no-unused-vars` | `warn` | Yes |

References:
- <https://eslint.org/docs/rules/no-unused-vars>

You can [close this issue](https://sider.review/gh/repos/451356574/pulls/12#issue-6549589) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).

</details>

2022-02-07 15:22 UTC, hsuj86 commented on src/pages/Cart/Cart.js
> +  const [inputCheck, setInputCheck] = useState(true);
> 이름을 모든 items가 다 체크되었는지를 잘 나타내는 이름으로 수정하면 좋겠네요!! 그리고 이부분은 굳이 state로 만들필요가 없을 것 같습니다! 라이브코드리뷰 시간에 한번 같이 볼게요

말씀하신대로 이름을 checkAllItem로 변경했습니다. 괜찮은지 궁금하네요.

그리고 연욱님이 state는 굳이 필요없다 하셔서 어떤 방법이 있을까 생각하다 useRef를 생각이 나서 사용해봤습니다. 
useRef를 사용해보니 개별 아이템들을 체크를 할 때는 괜찮았습니다. 하지만 useEffect를 사용한 부분에서는 set함수 대신 checkBoxRef.current.checked = true; 및 false;를 사용해보려 했으나 적용이 되지 않았습니다. 아래는 코드입니다.

`  useEffect(() => {
    const checkTrue = items.filter(item => item.is_check === true);
    if (checkTrue.length === items.length) {
      return checkBoxRef.current.checked = true;
    } else if (checkTrue.length < items.length) {
      return checkBoxRef.current.checked = false;
    } else return;
  }, [items]);`

분명 방법이 있을텐데 잘 모르겠습니다. 라이브코드리뷰 시간을 기대하겠습니다! 감사합니다

2022-02-07 15:27 UTC, hsuj86 commented on src/components/Nav/UserInfo.js
> +import React, { useEffect } from 'react';
> **[ESLint]** 'useEffect' is defined but never used. ([view](https://sider.review/gh/repos/451356574/pulls/12#issue-6549588))

삭제 완료

2022-02-07 15:29 UTC, hsuj86 commented on src/components/Nav/UserInfo.js
> +import React, { useEffect } from 'react';
> **[ESLint]** 'useEffect' is defined but never used. ([view](https://sider.review/gh/repos/451356574/pulls/12#issue-6549588))

삭제 완료

2022-02-07 15:36 UTC, hsuj86 commented
> 그리고 추가기능구현중이신가요?? 지금 이 브랜치는 마무리 짓고 추가기능은 새로운 브랜치에서 하시는게 좋아보입니다!

네 맞습니다. 지금 백엔드와 맞출 것이 있어 잠깐 대기 중 입니다. 
일단은 리뷰들 반영했고 말씀해주신대로 추가기능은 새로운 브랜치에서 하도록 하겠습니다. 감사합니다! 👍🏻

2022-02-07 15:37 UTC, hsuj86 commented on src/pages/Cart/Cart.js
> +import BASE_URL from '../Config';
> **[ESLint]** 'BASE_URL' is defined but never used. ([view](https://sider.review/gh/repos/451356574/pulls/12#issue-6549589))

백엔드와 데이터를 주고 받아야해서 잠시 주석 처리를 한 부분이 있습니다.
거기에 맞물려 있는 것이라 이것도 임시로 주석 처리를 하겠습니다.

2022-02-08 01:33 UTC, younuk23 commented
LGTM 👍

2022-02-08 01:34 UTC, younuk23 approved these changes

2022-02-08 01:34 UTC, merged