[29기 주지홍] 메인페이지 정렬 기능구현 및 브랜치 기능명으로 변경
wecode-bootcamp-korea/29-1st-BAMIN-SURVIVAL-frontend pull request #3
Opened 2022-01-25 08:28 UTC by jihongzzang

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 제품 페이지 일정 개수 초과시 자동으로 아래로 내려가게 하는 기능 구현
- 목데이터와 상수데이터를 활용해 제품 메인페이지 데이터 호출 및 정렬 기능
- 지금까지 구현한 내용에 대해 먼저 pr 작성했습니다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- flex wrap을 활용해 제품페이지 일정개수 초과시 자동으로 아래로 내려가게 기능을 구현하였습니다.
- 목데이터를 활용해 제품의 데이터를 메인페이지에 나타나도록 하였습니다.
- 상수데이터를 활용해 Section 부분의 제품 전체 갯수 및 분류카테고리를 만들었습니다.
- 분류카테고리 버튼을 누르면 제품들이 재정렬 되도록 만들었습니다. (useEffect 부분에서 `setIsClicked(data);` 해당 부분누락시 초기페이지에서 데이터가 나타나지 않는 현상을 파악했습니다. 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 상수데이터로 불러온 버튼을 따로따로 관리하는 법에 대해 알게된 것 같습니다.
- useEffect에서 사이클 대해 공부해보게 되는 계기가 되었습니다.
<br />

## :: 기타 질문 및 특이 사항
- 연욱멘토님과 한 대화에서 말씀해주신 방법이 이 방법이 맞는건지 좀 궁금합니다. 기능 단위로 브랜치를 파게되면서 feature/jihong => feature/main 으로 브랜치 이름을 바꾸었습니다.

2022-01-26 03:08 UTC, younuk23 reviewed
지홍님 이전 브랜치에서 리뷰 남긴 내용 여기서 반영해주시고 이전 브랜치에서 열어둔 PR은 close 해주세요

2022-01-27 07:03 UTC, younuk23 commented
리뷰 요청 전에 사이더 코멘트는 꼭 확인 및 해결해주세요~!

2022-01-27 07:35 UTC, younuk23 reviewed
고생하셨습니다 지홍님 리뷰 확인 및 반영해주세요!!
그리고 추가작업 진행중 라벨 붙어있는데 지금 이브랜치 여기서 마무리해도 될 것 같은데 가능하면 이브랜치마무리하고 새로운 기능은 새 브랜치에서 작업하시는걸 권장드립니다!

2022-01-27 07:35 UTC, younuk23 commented on src/pages/Jihong/Main.js
> +    }
```suggestion
    if (e.target.innerText === '높은가격순') {
      setItems(decend);
      return;
    } 
    if (e.target.innerText === '낮은가격순') {
      setItems(ascend);
      return;
    } 
    if (e.target.innerText === '최신순') {
      setItems(recent);
      return;
    }
```
early return 활용하면 else 구문은 필요 없습니다!

2022-01-27 07:35 UTC, younuk23 commented on src/pages/Jihong/MainComponents/Item/Item.js
> +  console.log(discount);
수정해주세요

2022-01-27 07:35 UTC, younuk23 commented on src/pages/Jihong/MainComponents/Section/Carousel.js
> +              onClick={() => moveDot(idx)}
응용 잘 하셨네요 👍

2022-01-27 07:50 UTC, jihongzzang commented
> 리뷰 요청 전에 사이더 코멘트는 꼭 확인 및 해결해주세요~!

네 다음부터는 꼭 확인하겠습니다.

2022-01-27 14:29 UTC, jihongzzang commented on src/pages/Jihong/Main.js
> +    }
수정사항 구현완료!

2022-01-27 14:30 UTC, jihongzzang commented on src/pages/Jihong/MainComponents/Item/Item.js
> +  console.log(discount);
수정사항 반영완료!

2022-01-28 02:07 UTC, younuk23 requested changes
고생하셨습니다 지홍님, 수정해야되는 코멘트 하나 있습니다. 그것만 반영해주시고 여기 마무리지어도 될 것 같네요!

2022-01-28 02:07 UTC, younuk23 commented on src/pages/Mainpage/Main.js
> +  const [carouselItems, setCarouselItems] = useState([]);
지홍님 이 부분에서 carouselItems는 state가 될 필요가 없는 값으로 보입니다.
***
[공식문서 React로 사고하기](https://ko.reactjs.org/docs/thinking-in-react.html#step-3-identify-the-minimal-but-complete-representation-of-ui-state) 를 보시면 어떤 값들이 state가 되어야하는지에 대해 적혀있습니다.

> 각각 살펴보고 어떤 게 state가 되어야 하는 지 살펴봅시다. 이는 각 데이터에 대해 아래의 세 가지 질문을 통해 결정할 수 있습니다
> 

> 1. 부모로부터 props를 통해 전달됩니까? 그러면 확실히 state가 아닙니다.
> 

> 2. 시간이 지나도 변하지 않나요? 그러면 확실히 state가 아닙니다.
> 

> 3. 컴포넌트 안의 다른 state나 props를 가지고 계산 가능한가요? 그렇다면 state가 아닙니다.
>
***
위 문서 읽어보시면 carouselItems같은 경우에는 결과적으로 items의 값을 통해서 계산 가능한 값이기 때문에 state가 될 필요가 없습니다.

그냥 일반 변수처럼 선언해서 사용하시면 될 듯 하네요
`carouseltems = items.filter(item => item.price > 70000).slice(0,4)`

2022-01-28 02:07 UTC, younuk23 commented on src/pages/Mainpage/Main.js
> +  };
할인된 가격을 기준으로 sorting 하고싶다면 sort안의 함수 로직을 바꾸면 될 것 같네요!

질문주신 부분의 setA함수 안의 callback에서는 아무것도 return 하고 있지 않습니다. 그래서 map 함수의 결과값이 undefined만 모여있는 식으로 되는 것 같네요!

2022-01-28 06:26 UTC, jihongzzang commented on src/pages/Mainpage/Main.js
> +  const [carouselItems, setCarouselItems] = useState([]);
연욱님 버튼이 눌렸을때 items의 배열이 바뀌면서 items의 state의 상태가 변하게 되는데 carouselItems 를 밖에서 선언하게 된다면 기존 배열의 영향을 받아서 계속 바뀌지 않을까요?

2022-01-28 08:13 UTC, jihongzzang commented on src/pages/Mainpage/Main.js
> +  const [carouselItems, setCarouselItems] = useState([]);
스테이트로 관리하면 안된다는걸 알았는데 그렇다면 슬라이드 이미지는 초기아이템값에만 영향을 받고 그뒤부터는 영향을 안받게 하고싶은데 이럴때는 어떤식으로 접근해야할까요 ㅠㅠ

2022-01-28 08:14 UTC, younuk23 commented on src/pages/Mainpage/Main.js
> +  const [carouselItems, setCarouselItems] = useState([]);
아 캐러셀 아이템은 고정되있길 원하시는군요,
일단 예전에 가이드해드렸던 것 처럼 버튼을 눌렸을때 items 원본 배열을 바꾸는 것이 아니라 sort function만 바꿔서 최종 props로 넘어가는 배열은 state가 아닌 items를 sorting한 새로운 변수를 넘기면 items는 원 상태가 유지되기 때문에 해결되는 문제로보이는데, 지금 상태에서는 그렇게 변환하시기 어렵다고 하시면 추후 도전과제로 남겨두고 일단 현상태 유지해도 되어보입니다!

2022-01-28 08:16 UTC, younuk23 commented on src/pages/Mainpage/Main.js
> +  const [carouselItems, setCarouselItems] = useState([]);
```jsx
carouseltems = items.filter(item => item.price > 70000).slice(0,4);
sortedItems = [...items].sort(//이부분 callback 현재 선택된 버튼에 따라 다르게 넣어주기))

~~~
        <ItemList items={sortedItmes} />
```

2022-01-28 08:16 UTC, younuk23 commented on src/pages/Mainpage/Main.js
> +  const [carouselItems, setCarouselItems] = useState([]);
간략한 예시 코드 추가해드렸습니다! 한번 보고 연휴기간동안 도전해보세요!!

2022-01-28 08:16 UTC, younuk23 commented
이 브랜치는 이제 머지하겠습니다 주홍님!

2022-01-28 08:17 UTC, merged

2022-01-28 08:17 UTC, younuk23 commented on src/pages/Mainpage/Main.js
> +  const [carouselItems, setCarouselItems] = useState([]);
이거 라이브코드리뷰시간에 한번 다뤄드릴게요!