[29기 주지홍]제품 상세페이지
wecode-bootcamp-korea/29-1st-BAMIN-SURVIVAL-frontend pull request #8
Opened 2022-01-29 04:18 UTC by jihongzzang

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 메인페이지와 연계하여 제품 상세페이지 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-02-07 08:03 UTC, younuk23 requested changes
지홍님 고생하셨습니다!! 어려운 부분 구현 계획 잘 세워가시면서 구현하려고 노력하신 것 같아서 너무 좋네요!! 몇가지 코멘트 드렸습니다 확인하시고 반영해주세요!

2022-02-07 08:03 UTC, yeonuk-hwang commented on src/pages/Detailpage/DetailComponents/ImageModal/ImageModal.js
> +    <div className="modalWrraper">
modalWrapper는 항상 렌더링되도록 처리하신 이유가 있나요??

2022-02-07 08:03 UTC, yeonuk-hwang commented on src/pages/Detailpage/DetailComponents/ProductBasicInfo/ProductBasicInfo.js
> +          {typeof discount_price === 'number'
discount_price의 type으로 조건을 설정하신 이유가 있을까요?? 만약 undefined거나 null로 온다면 그냥 truthy값일때만으로 조건을 설정하는게 좀 더 좋아보이네요!

2022-02-07 08:03 UTC, yeonuk-hwang commented on src/pages/Detailpage/detailpage.js
> +    fetch(`http://localhost:3003/result?id=${id}`, {
localhost:3000은 생략가능합니다! 생략하고 절대경로 시작하게 되면 자연스럽게 현재 프로젝트가 실행되고 있는 URL로 인식이 됩니다.
오히려 기입하게 되면 localhost:3000이 아닌 다른 URL에서 프로젝트가 실행될 때 에러가 발생할 수 있습니다

2022-02-07 08:03 UTC, yeonuk-hwang commented on src/pages/Detailpage/detailpage.js
> +  const users = [
- 이 값 같은 경우에는 매 rendering 마다 새롭게 선언되고 할당될 필요는 없어보입니다.
- 이런 상수데이터를  함수형 컴포넌트 본문 안에서 선언하게 되면 rendering이 일어날때 마다 매번 데이터를 만들고 변수에 값을 할당하는 연산이 일어나게 됩니다.
- 따라서 성능에 악영향을 미칠 수 있습니다.
- 컴포넌트가 사용하는 데이터라고 컴포넌트 안에만 위치할 필요는 없습니다
- 통상 이런 상수데이터같은 경우에는 여러 컴포넌트에서 동시에 사용하는 데이터라면 별도 파일로 분리하거나,이 컴포넌트 안에서만 사용하는 데이터라면 컴포넌트 하단에 작성해줍니다
- 상수데이터의 네이밍은 상수데이터임을 표시하기 위해서 UPPERCASER + snake_case 로 작성해주는게 컨벤션입니다
- 위 데이터의 경우에는 상수데이터로 보여서 위 내용에 맞게 수정해주시는게 좋겠네요!

2022-02-07 08:03 UTC, yeonuk-hwang commented on src/pages/Detailpage/detailpage.js
> +  useEffect(() => {
다른 문맥들끼리는 공백 한 줄 부여해주시는게 좋습니다!

2022-02-07 08:03 UTC, yeonuk-hwang commented on src/pages/Detailpage/DetailComponents/Rate/Rate.js
> +    <button className="starBtn" onClick={() => isLikeClick()}>
```suggestion
    <button className="starBtn" onClick={isLikeClick}>
```
굳이 새로운 함수 하나 더 만들지말고 함수 그대로 이벤트리스너로 추가해줘도 되보이네요!

2022-02-07 08:03 UTC, yeonuk-hwang commented on src/pages/Detailpage/DetailComponents/ProductDetail/ProductDetail.js
> +      userReviews.map(x => (x.id === id ? { ...x, comment: comment } : x))
x보다는 명확한 이름을 지어주시는게 좋아보이네요!

2022-02-07 08:03 UTC, yeonuk-hwang commented on src/pages/Detailpage/DetailComponents/ProductDetail/ProductDetail.js
> +};
컴포넌트 자체가 너무 방대하고 복잡해서 읽기가 조금 힘들어이네요! 적절하게 분리해주는게 좋아보입니다

2022-02-07 08:03 UTC, yeonuk-hwang commented on src/pages/Detailpage/DetailComponents/ProductInfo/ProductInfo.js
> +  const [addCartItem, setAddCartItem] = useState({
[공식문서 React로 사고하기](https://ko.reactjs.org/docs/thinking-in-react.html#step-3-identify-the-minimal-but-complete-representation-of-ui-state) 를 보시면 어떤 값들이 state가 되어야하는지에 대해 적혀있습니다.

> 각각 살펴보고 어떤 게 state가 되어야 하는 지 살펴봅시다. 이는 각 데이터에 대해 아래의 세 가지 질문을 통해 결정할 수 있습니다
> 

> 1. 부모로부터 props를 통해 전달됩니까? 그러면 확실히 state가 아닙니다.
> 

> 2. 시간이 지나도 변하지 않나요? 그러면 확실히 state가 아닙니다.
> 

> 3. 컴포넌트 안의 다른 state나 props를 가지고 계산 가능한가요? 그렇다면 state가 아닙니다.
>
***
props로 받은 값을 다시 state로 만드는 것 같네요 이렇게 되면 나중에 디버깅하기가 더 힘들어집니다!

2022-02-07 08:03 UTC, yeonuk-hwang commented on src/pages/Detailpage/DetailComponents/ProductInfo/ProductInfo.js
> +        )
setQuantityInput이 인자로 받을 수 있는 건 하나 뿐입니다.
두번째 인자인 setAddCartItem 같은 경우에는 인자로서의 역할은 하지않고 단순 함수호출인 것 같네요! 그렇다면 굳이 인자로 넘길 필요도 없고, 넘기는 동작으로 인해 다른 사람들에게 혼란을 불러일으킬 수 있을 것 같네요

2022-02-07 08:03 UTC, yeonuk-hwang commented on src/pages/Detailpage/DetailComponents/ProductInfo/ProductInfo.js
> +  const onClick = e => {
onClick처럼 발생하는 시점을 함수 이름으로 사용하기보다는, 함수가 어떤 동작을 하는지가 이름에서 드러나도록 지어주세요!

2022-02-07 08:03 UTC, younuk23 commented on src/pages/Detailpage/DetailComponents/ProductInfo/ProductInfo.js
> +    }
```suggestion
    if (e.key === 'Enter') checkNumber()
    return;
```

2022-02-07 08:03 UTC, yeonuk-hwang commented on src/pages/Detailpage/DetailComponents/ProductInfo/ProductInfo.js
> +    typeof quantityInput === 'string' && Number(quantityInput) > 0
이부분도 type이 string인지로 조건을 검사하는건 다소 위험해보이네요!

2022-02-07 08:03 UTC, yeonuk-hwang commented on src/pages/Detailpage/DetailComponents/ProductInfo/ProductInfo.js
> +          )
위쪽에 드린 인자 관련 코멘트와 동일한 부분인것 같습니다! 전반적으로 수정해주세요!!

2022-02-07 08:03 UTC, younuk23 commented on src/pages/Detailpage/DetailComponents/ProductInfo/ProductInfo.js
> +export default ProductInfo;
여기도 컴포넌트 분리가 되면 좀 더 읽기 좋겠네요!

2022-02-07 08:04 UTC, younuk23 commented
그리고, 추가기능구현은 다른 브랜치에서 진행하시는게 좋을 것 같습니다! 이미 지금 분량만으로도 브랜치가 다소 방대해보이네요!

2022-02-07 11:32 UTC, jihongzzang commented
> 그리고, 추가기능구현은 다른 브랜치에서 진행하시는게 좋을 것 같습니다! 이미 지금 분량만으로도 브랜치가 다소 방대해보이네요!

2022-02-07 11:54 UTC, jihongzzang commented on src/pages/Detailpage/DetailComponents/ProductInfo/ProductInfo.js
> +  const onClick = e => {
완료!

2022-02-07 11:54 UTC, jihongzzang commented on src/pages/Detailpage/detailpage.js
> +  useEffect(() => {
반영 완료!

2022-02-07 11:55 UTC, jihongzzang commented on src/pages/Detailpage/DetailComponents/ImageModal/ImageModal.js
> +    <div className="modalWrraper">
따로 이유는 없습니다. 클릭 될시에만 처리가 되면 좋을 것 같네요!!

2022-02-07 11:57 UTC, jihongzzang commented on src/pages/Detailpage/detailpage.js
> +    fetch(`http://localhost:3003/result?id=${id}`, {
`$ npm i -g json-server` 설치후 json-server --watch ./public/data/Jihong/itemListData.json --port 3003  목데이터를 이렇게 넣어놓고 썼는데 이런경우에도 생략이 가능한지 궁금합니다.

2022-02-07 11:57 UTC, jihongzzang commented on src/pages/Detailpage/detailpage.js
> +  useEffect(() => {
반영완료

2022-02-07 11:57 UTC, jihongzzang commented on src/pages/Detailpage/DetailComponents/ProductInfo/ProductInfo.js
> +  const onClick = e => {
반영완료

2022-02-07 11:58 UTC, jihongzzang commented on src/pages/Detailpage/DetailComponents/ProductInfo/ProductInfo.js
> +    }
반영완료!

2022-02-07 12:12 UTC, jihongzzang commented on src/pages/Detailpage/DetailComponents/ProductInfo/ProductInfo.js
> +    typeof quantityInput === 'string' && Number(quantityInput) > 0
해당 홈페이지 인풋창에서 입력된 최종 값이 숫자가 아니라면 알러트창이 생기고 해당 인풋의 밸류값을 1로 고정하는 변화를 발견하고 그대로 구현해보고 싶어서 접근하는 과정에서 입력은 스트링타입이고 "3" 이런부분을 Number로 바꿔서 해당조건을 만족하는 경우만 상태가 변화하고 싶어서 작성하게 되었는데 정규표현식으로 작성하는것이 더 좋을까요

2022-02-07 14:36 UTC, jihongzzang commented on src/pages/Detailpage/DetailComponents/ProductBasicInfo/ProductBasicInfo.js
> +          {typeof discount_price === 'number'
백엔드에서 데이터를 받아오기 dicount_price 항목에 빈 스트링값을 줬던 것으로 기억하고 이과정에서 조건부 렌더링을 걸었던것 같습니다. 
현제는 백엔드에서 discount_price 이지만 백엔드 데이터에서 판매가격을 할인이 있던 없던 discount_price로 네이밍해서 후에 오해의 소지가 있을수도 있을 것 같습니다.

2022-02-07 14:38 UTC, jihongzzang commented on src/pages/Detailpage/detailpage.js
> +  const users = [
현재 상수데이터는 아니고 시간관계상 분리가 여유치 않아 진행해보았었습니다. 제 생각으로는 제품상세페이지에 해당제품의 리뷰를 쓴 유저의 정보가 담겨있어야 하는것 같고 리뷰를 쓰게되면 데이터가 수정된다고 생각해 mock 데이터로 바꾸어 진행중인 상태입니다.!

2022-02-07 14:42 UTC, jihongzzang commented on src/pages/Detailpage/DetailComponents/Rate/Rate.js
> +    <button className="starBtn" onClick={() => isLikeClick()}>
반영완료

2022-02-07 14:44 UTC, jihongzzang commented on src/pages/Detailpage/DetailComponents/ProductInfo/ProductInfo.js
> +export default ProductInfo;
ProductInfo 컴포넌트를 현재 분리한 상태보다 조금 더 분리하라는 이야기인지 궁금합니다.

2022-02-07 14:48 UTC, jihongzzang commented on src/pages/Detailpage/DetailComponents/ProductInfo/ProductInfo.js
> +  const [addCartItem, setAddCartItem] = useState({
아하 이부분은 저는 상품 상세창에서 인자로 받는 props 중에 장바구니로 넘어갈때 필요없는 정보들도 존재한다고 생각했습니다. 따라서 처음에 addCartItem 이라는 변수를 설정해서 값을 담았는데 수량을 변경하는 상황과 옵션을 선택하게 되는 상황이 생기면서 해당 값은 바뀌어야 된다고 생각을 하게 되었습니다.  또한 프롭스로 받아온 객체의 밸류값을 특정상황에서 값을 바꿔서 넘겨주는것이 가능한지 궁금하고 이 부분이 많이 어려운것 같습니다.

2022-02-07 14:51 UTC, jihongzzang commented on src/pages/Detailpage/DetailComponents/ProductInfo/ProductInfo.js
> +        )
약간 제가 생각한 부분으로는 이부분에서 Input값이 바뀌면서 동시에 AddcartItem의 값도 변경되야 된다고 생각을해서 이렇게 콜백함수? 이런개념으로 생각해서 해보았는데 어떤식으로 접근해야하는지 어려운것 같습니다. 상세페이지를 진행하는 과정에서 사용자가 옵션이라던지 수량이라던지 이런 값이 바뀌게 되면서 화면에 값들이 다이나믹 하게 바뀌고 그러한 바뀐 데이터들을 백엔드로 넘겨야하는지가 궁금하고 어떤메커니즘으로 흘러가는지에 대한 감이 잡히지 않는것 같습니다.

2022-02-08 04:15 UTC, jihongzzang commented on src/pages/Detailpage/DetailComponents/ProductDetail/ProductDetail.js
> +};
분리완료

2022-02-09 04:24 UTC, jihongzzang commented on src/pages/Detailpage/DetailComponents/ImageModal/ImageModal.js
> +    <div className="modalWrraper">
이부분은 해결하고싶은데 useEffect의 사용법이 익숙치 않아 조금 힘든것 같습니다. 모달이 눌렸을때만 실행하고싶은데 그렇다면 effecthook 안에 컴포넌트를 넣어야하는건지 좀 궁금합니다.

2022-02-10 02:03 UTC, younuk23 reviewed
LGTM 👍

2022-02-10 02:03 UTC, younuk23 commented on src/pages/Detailpage/DetailComponents/ImageModal/ImageModal.js
> +    <div className="modalWrraper">
이부분 해결 안되셨으면 정리해서 라운지에서 질문주시면 답변 드리겠습니다~!

2022-02-10 02:03 UTC, merged